"""
Situation tab — task cards with progress tracking and exports.
"""

import streamlit as st
import pandas as pd
from datetime import datetime, timedelta


def _risk_class(fp):
    if fp >= 0.7: return "high"
    if fp >= 0.4: return "moderate"
    return "low"

def _risk_color(fp):
    if fp >= 0.7: return "#DC2626"
    if fp >= 0.4: return "#D97706"
    return "#0F6E56"


def _generate_deadline_ics(df_risk, start_date):
    lines = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//Cadence//Deadlines//EN"]
    for _, row in df_risk.iterrows():
        name = row["name"]
        days = int(row["days_left"])
        est = float(row["est_hours"])
        deadline_date = start_date + timedelta(days=days)
        lines.extend([
            "BEGIN:VEVENT",
            f"DTSTART;VALUE=DATE:{deadline_date.strftime('%Y%m%d')}",
            f"DTEND;VALUE=DATE:{(deadline_date + timedelta(days=1)).strftime('%Y%m%d')}",
            f"SUMMARY:DEADLINE: {name}",
            f"DESCRIPTION:{name} — {est}h estimated. Deadline day.",
            f"UID:deadline-{name.replace(' ','-')}-{deadline_date.strftime('%Y%m%d')}@cadence",
            "BEGIN:VALARM", "TRIGGER:-P1D", "ACTION:DISPLAY",
            f"DESCRIPTION:{name} is due tomorrow", "END:VALARM",
            "END:VEVENT",
        ])
    lines.append("END:VCALENDAR")
    return "\n".join(lines)


def _generate_pdf_report(df_risk, schedule_df, stress, available_hours, start_date):
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib import colors
        from reportlab.lib.units import inch
        import io

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter,
            leftMargin=0.75*inch, rightMargin=0.75*inch)
        styles = getSampleStyleSheet()
        story = []
        story.append(Paragraph("Cadence — Workload Report", styles['Title']))
        story.append(Paragraph(
            f"Generated {datetime.now().strftime('%B %d, %Y')} | "
            f"Capacity: {available_hours}h/day | Stress Index: {stress}/100",
            styles['Normal']))
        story.append(Spacer(1, 20))
        story.append(Paragraph("Task Overview", styles['Heading2']))
        story.append(Spacer(1, 8))

        table_data = [["Task", "Hours", "Days Left", "Risk", "Status"]]
        for _, row in df_risk.iterrows():
            fp = round(float(row["failure_probability"]) * 100, 1)
            status = "High Risk" if fp >= 70 else ("Moderate" if fp >= 40 else "On Track")
            table_data.append([
                str(row["name"])[:35],
                f"{row['est_hours']}h",
                str(int(row["days_left"])),
                f"{fp}%",
                status,
            ])

        col_widths = [2.8*inch, 0.7*inch, 0.7*inch, 0.7*inch, 0.9*inch]
        t = Table(table_data, colWidths=col_widths)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0C2829')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F0F4F5')]),
        ]))
        story.append(t)
        story.append(Spacer(1, 20))

        deadline_risks = schedule_df.attrs.get("deadline_risks", [])
        if deadline_risks:
            story.append(Paragraph("Deadline Risks", styles['Heading2']))
            for risk in deadline_risks:
                story.append(Paragraph(
                    f"- {risk['task']}: {risk['unfinished_hours']}h unfinished by Day {risk['deadline_day']}",
                    styles['Normal']))

        story.append(Spacer(1, 20))
        story.append(Paragraph("Generated by Cadence — Workload Intelligence", styles['Italic']))
        doc.build(story)
        return buf.getvalue()
    except ImportError:
        return None


def render_overview(df_risk, schedule_df, available_hours, planning_horizon, mode):
    from risk_model import compute_weighted_stress

    st.markdown("## Task overview")

    for i, row in df_risk.iterrows():
        fp = float(row["failure_probability"])
        risk_cls = _risk_class(fp)
        risk_col = _risk_color(fp)
        fp_pct = round(fp * 100, 1)
        est_h = float(row["est_hours"])
        task_name = row["name"]
        completed = st.session_state.progress.get(task_name, 0.0)
        pct = min(100, (completed / est_h * 100)) if est_h > 0 else 0
        dep_tag = " · Dependency risk" if row.get("dependency_risk") else ""

        st.markdown(f"""
        <div class="task-card risk-{risk_cls}">
            <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px;">
                <div>
                    <div style="font-weight:600;font-size:15px;color:#0C2829;">{task_name}</div>
                    <div style="font-size:12px;color:#7A8B8D;margin-top:3px;">
                        {est_h}h estimated · {int(row['days_left'])} days left{dep_tag}
                    </div>
                </div>
                <div style="display:flex;align-items:center;gap:8px;">
                    <span class="risk-badge {risk_cls}">{fp_pct}% risk</span>
                    <span style="font-size:12px;color:#7A8B8D;">{completed}/{est_h}h</span>
                </div>
            </div>
            <div style="height:4px;background:#EEF1F2;border-radius:2px;overflow:hidden;">
                <div style="width:{pct}%;height:100%;background:{risk_col};border-radius:2px;"></div>
            </div>
        </div>
        """, unsafe_allow_html=True)

        col_prog, col_del = st.columns([5, 1])
        with col_prog:
            new_val = st.slider(
                f"Hours completed on {task_name}",
                min_value=0.0, max_value=est_h, value=completed,
                step=0.5, key=f"slider_{i}_{task_name}", label_visibility="collapsed")
            if new_val != completed:
                st.session_state.progress[task_name] = new_val
                st.rerun()
        with col_del:
            if st.button("Delete", key=f"del_{i}"):
                st.session_state.tasks.pop(i)
                st.session_state.progress.pop(task_name, None)
                st.rerun()

    st.markdown("---")
    st.markdown("### Export")
    col_ics, col_pdf = st.columns(2)

    with col_ics:
        ics = _generate_deadline_ics(df_risk, st.session_state.start_date)
        if ics:
            st.download_button("Download deadlines (.ics)", ics,
                "cadence_deadlines.ics", "text/calendar")

    with col_pdf:
        if schedule_df is not None:
            stress = compute_weighted_stress(df_risk)
            pdf = _generate_pdf_report(df_risk, schedule_df, stress, available_hours, st.session_state.start_date)
            if pdf:
                st.download_button("Download report (.pdf)", pdf,
                    "cadence_report.pdf", "application/pdf")